export const SITE_URL = 'https://aimeesummers.co.uk'
export const FACEBOOK_URL = 'https://www.facebook.com/profile.php?id=61577465844833'
export const INSTAGRAM_URL = 'https://www.instagram.com/conveyancingwithaimee?igsh=Y3ZjanpjeTBkNHpw&utm_source=qr'
export const WHATSAPP_URL = 'https://wa.me/447592769978'
export const EMAIL_ADDRESS = 'aimee@hudsonconveyancing.co.uk'
export const CALENDLY_URL = 'https://calendly.com/aimee-hudsonconveyancing'
